-- Revising the Select Query I
SELECT * FROM CITY WHERE CITY.POPULATION>100000 AND CITY.COUNTRYCODE = "USA";

-- Revising the Select Query II
SELECT NAME FROM CITY WHERE CITY.POPULATION>120000 AND CITY.COUNTRYCODE = "USA";

-- Select All
SELECT * FROM CITY;